apiVersion: apps/v1
kind: Deployment
metadata:
  name: rottenlama-frontend-stable
  labels:
    app: rottenlama-frontend
    version: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rottenlama-frontend
      version: stable
  template:
    metadata:
      labels:
        app: rottenlama-frontend
        version: stable
    spec:
      containers:
      - name: rottenlama-frontend
        image: airwa1l/rottenlama-frontend:stable
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20