apiVersion: apps/v1
kind: Deployment
metadata:
  name: rottenlama-frontend-canary
  labels:
    app: rottenlama-frontend
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rottenlama-frontend
      version: canary
  template:
    metadata:
      labels:
        app: rottenlama-frontend
        version: canary
    spec:
      containers:
      - name: rottenlama-frontend
        image: airwa1l/rottenlama-frontend:canary
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20